# Generated by Django 2.0.7 on 2018-07-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fname',
        ),
    ]
