# Generated by Django 2.0.7 on 2018-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_teacher_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
