# Generated by Django 2.0.7 on 2018-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180712_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('male', 1), ('female', 2)], default=1),
        ),
    ]
