# Generated by Django 2.0.7 on 2018-07-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_date',
        ),
    ]
