# Generated by Django 2.0.7 on 2018-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_student_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('0', 'Select Gender'), ('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='0'),
        ),
    ]
