# Generated by Django 2.0.7 on 2018-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20180712_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='registerdate',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.TextField(max_length=60),
        ),
    ]
