# Generated by Django 2.0.7 on 2018-07-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180712_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='ClassStudent',
        ),
    ]
