# Generated by Django 2.0.7 on 2018-07-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20180712_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstudent',
            old_name='Class',
            new_name='_class',
        ),
    ]
