# Generated by Django 2.0.7 on 2018-07-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_section_sectionstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
    ]
