# Generated by Django 2.0.7 on 2018-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_section_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='class_id',
            new_name='class_pk',
        ),
    ]
