# Generated by Django 2.0.7 on 2018-07-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20180715_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='class_pk',
            new_name='class_id',
        ),
    ]
