# Generated by Django 2.0.7 on 2018-07-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20180715_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='class_id',
            new_name='_class',
        ),
    ]
