# Generated by Django 2.0.7 on 2018-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20180715_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image_1',
            field=models.ImageField(blank=True, default='', upload_to='questions/'),
        ),
    ]
