# Generated by Django 2.0.7 on 2018-07-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_class_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('subject_name', models.CharField(max_length=65)),
                ('description', models.TextField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField(max_length=13)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Class')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
