# Generated by Django 2.0.7 on 2018-07-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_subject_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('subject_name', models.CharField(max_length=65)),
                ('description', models.TextField(max_length=120)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Syllabus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
