# Generated by Django 2.0.7 on 2018-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20180716_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectSyllabus',
            new_name='Subject',
        ),
    ]
