# Generated by Django 2.0.7 on 2018-07-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20180716_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
