# Generated by Django 2.0.7 on 2018-07-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('obtained_marks', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMarkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('marks_type', models.IntegerField(choices=[('0', 'Select MarksType'), ('1', 'Theory'), ('2', 'Practical')], default=0)),
                ('total_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subjectmarks',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.SubMarkType'),
        ),
    ]
